
# Name your project! Project names should be lowercase and use underscores as spaces.
name: 'marketing_roas'
version: '1.0.0'
config-version: 2

# This sets the `raw-paths` directory. By default, you'll only get one model in each directory,
# but in subsequent runs Dbt will rebuild files in these directories
# which helps us improve our incremental builds.
# To find these directories, we recommend checking the `execute` block on the YAML Config.
profile: 'marketing_roas'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  marketing_roas:
    staging:
      +materialized: table
      +schema: analytics
    intermediate:
      +materialized: table
      +schema: analytics
    marts:
      +materialized: table
      +schema: analytics

vars:
  # Global variables
  start_date: '2014-10-21'
  end_date: '2014-10-31'
